### ISSUE TITLE
Checkpointing feature doesn't work 

### ISSUE THREAD

**Issue by johnugeorge** [argonne-lcf/dlio_benchmark#12]
Checkpointing is enabled in the config file but feature is broken. Below is the relevant parts of the sample config file that I used

```
workflow:
  generate_data: False
  train: True
  evaluation: True
  checkpoint: True

checkpoint:
  checkpoint_after_epoch: 2
  epochs_between_checkpoints: 2
  steps_between_checkpoints: 4
```
